name: Create and push commit

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create_commit:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    timeout-minutes: 10
    env:
      RELEASE_VERSION: ${{ inputs.release_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Update changelog
        run: |
          set -euxo pipefail
          changelog_items=$(python maint_tools/parse_changelog.py CHANGELOG.md $RELEASE_VERSION)
          git add CHANGELOG.md
          git commit --allow-empty -m "Update changelog for $RELEASE_VERSION"
          git tag $RELEASE_VERSION

          echo $changelog_items > release_changelog.txt
      - name: Push commit to GitHub
        run: |
          git push origin ${{ github.event.inputs.main_version }}
          git push origin $RELEASE_VERSION
      - name: Create release with tag
        run: |
          set -euxo pipefail
          if [[ $RELEASE_VERSION == *"b"* ]]; then
            gh release create $RELEASE_VERSION -t $RELEASE_VERSION --prerelease
          else
            gh release create $RELEASE_VERSION -t $RELEASE_VERSION
          fi
          gh release edit $RELEASE_VERSION --notes-file release_changelog.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
